### ISSUE TITLE
Componente - AboutUs 

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/portal#3]
**Descrição da melhoria:**
Implementação do componente AboutUs que será usado na página inicial do portal

**Como ela pode ser implementada:**
A implementação deve seguir o design proposto no figma. Este componente pode ser criado dentro da pasta src/components.

Em telas menores, a listagem dos items de comunidade, open source e empoderamento devem ter um scroll para os lados, não colocar os item um abaixo do outro.

**Imagens:**
![image](https://github.com/OpenDevUFCG/portal/assets/42751604/cbd37c5e-ba67-4c73-a68a-1192a68a6c24)

**Contexto adicional:**
[Link do figma contendo o design completo](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?type=design&node-id=0-1&mode=design&t=ti6CKzilWDSBWh9m-0)

**Comment by AmiltonCabral** [comment]
Fico com essa
