### ISSUE TITLE
Componente - CoreMember

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/portal#4]
**Descrição da melhoria:**
Implementação do componente CoreMember que será usado na página inicial do portal e na página da nossa história

**Como ela pode ser implementada:**
A implementação deve seguir o design proposto no figma. Este componente pode ser criado dentro da pasta src/components, já que este será utilizado em diversas páginas

Aconselho que esse componente receba como props as seguintes propriedades:
```
{
  name: <nome da pessoa>,
  github: <usuario do github>
}
```

Utilizando a [API do github](https://docs.github.com/en/rest?apiVersion=2022-11-28), a ideia é que ao receber o usuário do github nós possamos coletar a foto de perfil desse usuário do próŕio github.

⚠️ OBS: Quando o usuário colocar o mouse em cima da foto queremos que apareça um tooltip mostrando o nome da pessoa e quando o usuário clicar, ele deve ser redirecionado para o github da pessoa em questão

**Imagens:**
![image](https://github.com/OpenDevUFCG/portal/assets/42751604/fa4e4183-3944-4688-addc-5a9acea9d408)

**Contexto adicional:**
[Link do figma contendo o design completo](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?type=design&node-id=0-1&mode=design&t=ti6CKzilWDSBWh9m-0)

**Comment by andersonstv** [comment]
Olá, poderia ficar com essa issue?

**Comment by RodrigoEC** [comment]
Feito!
