### ISSUE TITLE
Componente - SubSection

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/portal#6]
**Descrição da melhoria:**
Implementação do componente SubSection que será usado na página inicial do portal

**Como ela pode ser implementada:**
A implementação deve seguir o design proposto no figma. Este componente pode ser criado dentro da pasta src/components.

Nesse componente, a ideia é ter um título e um textinho abaixo que será exibido, como é mostrado na imagem seguinte. 

Para tornar o componente generalizavel, sugiro receber como props do componente o seguinte objeto:

```js
props = {
  title: <titulo-da-sub-secao>,
  subtitulo: <texto-de-exibição>
}
```

**Imagens:**
![image](https://github.com/OpenDevUFCG/portal/assets/42751604/19bfe64a-d0dc-4175-8c78-5f8c1f6244ed)

**Contexto adicional:**
[Link do figma contendo o design completo](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?type=design&node-id=0-1&mode=design&t=ti6CKzilWDSBWh9m-0)

**Comment by laysasantos2** [comment]
gostaria de ficar com essa parte

**Comment by RodrigoEC** [comment]
Pode ficar!
